# Generated by Django 6.0.6 on 2026-07-11 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='goal',
            name='ai_milestones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('career', 'Career'), ('health', 'Health'), ('finance', 'Finance'), ('learning', 'Learning'), ('other', 'Other')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
